config/routes.rb
Gollum::Application.routes.draw do

  resources :pages, :except => [:index] do
    member do
      post 'preview'
    end
  end
  root :to => "pages#show"

end

app/models/page.rb
class Page < ActiveRecord::Base

  acts_as_nested_set

  # Temporarily hard coded
  FORMAT = :textile
  WIKI   = Rails.root.join("db", "wiki.git")


  before_create  :create_page
  before_update  :update_page
  before_destroy :delete_page

  attr_accessor :body, :change_comment

  def content
    page.formatted_data
  end

  def raw_content
    page.raw_data
  end

  def self.welcome
    Page.first(:conditions => {:name => 'Welcome'})
  end

  def author
    page.version.author.name.gsub(/<>/, '')
  end

  def date
    page.version.authored_date
  end

  def preview(data)
    wiki.preview_page('Preview', data, FORMAT).formatted_data
  end


  private

  def wiki
    @@golum ||= Gollum::Wiki.new(WIKI)
  end

  def page
    wiki.page(self.name)
  end

  def create_page
    wiki.write_page(name, FORMAT, body || '', {:message => self.change_comment, :name => 'tester', :author => 'tester'})
  end

  def update_page
    wiki.update_page(page, name, FORMAT, body || self.raw_content, {:message => self.change_comment, :name => 'tester', :author => 'tester'})
  end

  def delete_page
    wiki.delete_page(page, COMMIT)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :instantiate_controller_and_action_names
  after_filter  :store_location


  def get_layout
    request.xhr? ? nil : 'application'
  end

  protected

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

  private

  def store_location
    session[:return_to] = request.fullpath unless request.xhr?
  end

  def instantiate_controller_and_action_names
    @current_action = action_name
    @current_controller = controller_name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout :get_layout

  before_filter :find_page, :except => [:new, :show, :create]
  before_filter :find_body, :only => [:edit]

  def new
    @page = Page.new
  end

  def edit
  end

  def show
    @page = Page.find(params[:id] || Page.welcome)
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      flash[:notice] = "Successfully created page."
      redirect_to @page
    else
      render :action => 'new'
    end
  end

  def update
    if @page.update_attributes(params[:page])
      flash[:notice] = "Successfully updated page."
      redirect_to @page
    else
      render :action => 'edit'
    end
  end

  def destroy
    @page.destroy
    flash[:notice] = "Successfully destroyed page."
  end

  def preview
    render :text => @page.preview(params[:data])
  end

  private

  def find_page
    @page = Page.find(params[:id])
  end

  def find_body
    @page.body = params[:page][:body] rescue @page.raw_content
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bodytag_id
    "#{@current_controller}_#{@current_action}"
  end

  def cancel_link title = 'Cancel'
    return content_tag(:div, link_to(title, session[:return_to], :class => 'cancel'))
  end

end

app/helpers/pages_helper.rb
module PagesHelper

  def breadcrumbs(page)
    s = []
    page.ancestors.each do |p|
      s << content_tag(link_to p.name, page_path(p))
    end
    raw(s.join(' '))
  end

end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Socdoc
    = raw ajaxlibs_include :jquery
    = include_stylesheets :common
    = include_javascripts :common
    = csrf_meta_tag
  %body{:id => bodytag_id}
    #container
      #flash_notice{:style => 'display:none;'}= flash[:notice]

      #toc.span-12= render :partial => 'pages/index'
      #content.span-12.last= yield

app/views/pages/_form.haml
= form_for(@page) do |f|

  %p
    = f.label :name
    = f.text_field :name

  %p
    - unless @page.new_record?
      = link_to 'Edit mode', '#', :id => 'write'
      = link_to 'Preview mode', preview_page_path(@page), :id => 'preview'
    #write_area
      = f.textile_editor :body
    #preview_area.hide

  %p
    = f.label 'Describe this change (optional)'
    = f.text_field :change_comment

  .actions
    = f.submit
    = cancel_link

  = raw(textile_editor_initialize(:framework => :jquery))

app/views/pages/_index.haml
%h3 Table of contents

%ul#pages_list= render Page.root

app/views/pages/_page.haml
%li{:id => dom_id(page), :class => "level_#{page.level}"}

  = link_to page.name, page_path(page)
  = link_to '(Add)', new_page_path, :rel => dom_id(page)

  - unless page.children.empty?
    %ul= render page.children

app/views/pages/destroy.js.erb
<% unless @page.errors.any? -%>
  $("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");
  $("#flash_notice").show(300);
  $("#<%= dom_id(@page)%>").fadeOut('fast');
<% end -%>

app/views/pages/edit.haml
%h1="Editing page \"#{@page.name}\""
= render 'form'

app/views/pages/new.haml
%h1 New page
= render 'form'

app/views/pages/show.haml
%small
  = breadcrumbs(@page)

%h4
  = "Page name: #{@page.name}"
  = link_to '(Edit)', edit_page_path(@page)
  = link_to '(Destroy)', @page, :remote => true, :confirm => 'Are you sure?', :method => :delete

  %small= "Last edited by #{@page.author} #{time_ago_in_words(@page.date)} ago."

%hr

= raw(@page.content)

%hr